name: Auto approve
run-name: ${{ github.actor }} is trying to approve
on:
  pull_request_target:
    branches: [ "main" ]

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: ls -1
  auto-approve:
    runs-on: ubuntu-latest
    if: github.actor == 'rfguimaraes' && github.event.pull_request.head.repo.full_name == 'testautopr/testautopr' && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'updates' && github.event.pull_request.draft == false
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v3
  just_echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is interesting..."
